//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTechNoLoGy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class binhLuanBV
    {
        public int MaBL { get; set; }
        public string MaBV { get; set; }
        public string TaiKhoan { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayBL { get; set; }
    
        public virtual baiViet baiViet { get; set; }
        public virtual taiKhoanTV taiKhoanTV { get; set; }
    }
}
