//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTechNoLoGy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoHang
    {
        public int maGiaoHang { get; set; }
        public string soDH { get; set; }
        public string maShipper { get; set; }
        public System.DateTime ngayGiao { get; set; }
        public int maTrangThai { get; set; }
        public string ghiChu { get; set; }
    
        public virtual donHang donHang { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual TrangThaiGiaoHang TrangThaiGiaoHang { get; set; }
    }
}
