//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopTechNoLoGy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhuyenMai
    {   
        
        public string maKM { get; set; }
        public string maSP { get; set; }
        public string taiKhoan { get; set; }
        public string noiDung { get; set; }
        public System.DateTime ngayBatDau { get; set; }
        public System.DateTime ngayKetThuc { get; set; }
        public Nullable<int> giamGia { get; set; }
        public string ghiChu { get; set; }
        public Nullable<bool> trangThai { get; set; }
    
        public virtual sanPham sanPham { get; set; }
        public virtual taiKhoanTV taiKhoanTV { get; set; }

    }
}
